# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-04 11:31
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawyer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('court', models.CharField(blank=True, max_length=20, null=True, verbose_name='交付单位')),
                ('remarks', ckeditor.fields.RichTextField(blank=True, verbose_name='理由')),
            ],
            options={
                'verbose_name': '重新司法鉴定申请',
                'verbose_name_plural': '重新司法鉴定申请',
            },
        ),
        migrations.CreateModel(
            name='Bail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='申请人姓名')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='地址')),
                ('tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='电话')),
                ('requests', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='申请事项')),
                ('case', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='事实与理由')),
                ('court', models.CharField(blank=True, max_length=20, null=True, verbose_name='交付单位')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '取保候审申请书',
                'verbose_name_plural': '取保候审申请书',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='案件委托阶段')),
                ('enter_date', models.DateField(blank=True, null=True, verbose_name='创建时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '刑事业务流程',
                'verbose_name_plural': '刑事业务流程',
            },
        ),
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.NullBooleanField(default=0, verbose_name='是否订阅')),
                ('case_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='刑事案件编号')),
                ('openid', models.CharField(blank=True, max_length=120, verbose_name='唯一标识')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='委托人')),
                ('sex', models.CharField(choices=[('1', '男'), ('2', '女')], default='1', max_length=20, verbose_name='性别')),
                ('age', models.CharField(blank=True, max_length=10, verbose_name='年龄')),
                ('nation', models.CharField(blank=True, max_length=10, verbose_name='民族')),
                ('occupation', models.CharField(blank=True, max_length=20, verbose_name='职业')),
                ('idcard', models.CharField(blank=True, max_length=50, verbose_name='身份证号')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='住址')),
                ('tel', models.CharField(blank=True, max_length=50, verbose_name='联系电话')),
                ('nail_address', models.CharField(blank=True, max_length=200, verbose_name='现住址')),
                ('case', models.CharField(blank=True, max_length=1000, verbose_name='涉嫌罪名')),
                ('defendant', models.CharField(blank=True, max_length=50, verbose_name='犯罪嫌疑人或被告人')),
                ('defendants', models.CharField(blank=True, max_length=50, verbose_name='共同犯罪嫌疑人或被告人')),
                ('stage', models.CharField(blank=True, choices=[('1', '咨询阶段'), ('2', '侦查阶段'), ('3', '审查起诉'), ('4', '一审审判阶段'), ('5', '二审审判阶段'), ('6', '再审阶段')], default='1', max_length=50, verbose_name='案件所处阶段')),
                ('case_office', models.CharField(blank=True, max_length=50, verbose_name='办案机关')),
                ('Trial_level', models.CharField(choices=[('1', '一审'), ('2', '二审'), ('4', '再审'), ('3', '一审，二审'), ('5', '二审，再审')], default='1', max_length=20, verbose_name='审级')),
                ('enter_date', models.DateField(blank=True, null=True, verbose_name='归档时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Criminals', to=settings.AUTH_USER_MODEL, verbose_name='承办律师')),
            ],
            options={
                'verbose_name': '登记表',
                'verbose_name_plural': '登记表',
            },
        ),
        migrations.CreateModel(
            name='Criminal_letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='编号')),
                ('court', models.CharField(blank=True, max_length=20, null=True, verbose_name='交付单位')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='犯罪嫌疑人或被告人')),
                ('case', models.CharField(blank=True, max_length=1000, null=True, verbose_name='案由')),
                ('court_picture', models.FileField(blank=True, upload_to='Court_letter', verbose_name='文件/图片')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Criminal_letter', to='criminal.Business', verbose_name='案件委托阶段')),
                ('civil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='criminal.Criminal', verbose_name='刑事案件编号')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Criminal_letters', to=settings.AUTH_USER_MODEL, verbose_name='承办律师')),
            ],
            options={
                'verbose_name': '律师事务所出庭函',
                'verbose_name_plural': '律师事务所出庭函',
            },
        ),
        migrations.CreateModel(
            name='CriminalAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nail_name', models.CharField(max_length=50, verbose_name='甲方名称')),
                ('nail_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='地址')),
                ('nail_tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='电话')),
                ('nail_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='身份证号')),
                ('b_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='住址')),
                ('b_tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='电话')),
                ('case', models.CharField(blank=True, max_length=1000, verbose_name='涉嫌罪名')),
                ('defence_fee', models.CharField(blank=True, max_length=50, null=True, verbose_name='律师费(元)')),
                ('agency_fee', models.CharField(max_length=50, verbose_name='律师费(大写元)')),
                ('total', models.CharField(blank=True, max_length=50, null=True, verbose_name='共计(元)')),
                ('enter_date', models.DateField(blank=True, null=True, verbose_name='签订日期')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CriminalAgent', to='criminal.Business', verbose_name='案件委托阶段')),
                ('civil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='criminal.Criminal', verbose_name='刑事案件编号')),
                ('law', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='lawyer.Law', verbose_name='乙方律师事务所')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CriminalAgents', to=settings.AUTH_USER_MODEL, verbose_name='承办律师')),
            ],
            options={
                'verbose_name': '委托代理协议',
                'verbose_name_plural': '委托代理协议',
            },
        ),
        migrations.CreateModel(
            name='CriminalAgents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nail_name', models.CharField(max_length=50, verbose_name='甲方名称')),
                ('nail_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='地址')),
                ('nail_tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='电话')),
                ('nail_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='身份证号')),
                ('b_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='住址')),
                ('b_tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='电话')),
                ('case', models.CharField(blank=True, max_length=1000, verbose_name='涉嫌罪名')),
                ('defence_fee', models.CharField(blank=True, max_length=50, null=True, verbose_name='律师费(元)')),
                ('agency_fee', models.CharField(max_length=50, verbose_name='律师费(大写元)')),
                ('total', models.CharField(blank=True, max_length=50, null=True, verbose_name='共计(元)')),
                ('enter_date', models.DateField(blank=True, null=True, verbose_name='签订日期')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CriminalAgents', to='criminal.Business', verbose_name='案件委托阶段')),
                ('civil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='criminal.Criminal', verbose_name='刑事案件编号')),
                ('law', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='lawyer.Law', verbose_name='乙方律师事务所')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CriminalAgentss', to=settings.AUTH_USER_MODEL, verbose_name='承办律师')),
            ],
            options={
                'verbose_name': '委托代理协议(二审)',
                'verbose_name_plural': '委托代理协议(二审)',
            },
        ),
        migrations.CreateModel(
            name='Defendant_letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='编号')),
                ('court', models.CharField(blank=True, max_length=20, null=True, verbose_name='交付单位')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='犯罪嫌疑人或被告人')),
                ('case', models.CharField(blank=True, max_length=1000, null=True, verbose_name='案由')),
                ('court_picture', models.FileField(blank=True, upload_to='Court_letter', verbose_name='文件/图片')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Defendant_letter', to='criminal.Business', verbose_name='案件委托阶段')),
                ('civil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='criminal.Criminal', verbose_name='刑事案件编号')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Defendant_letters', to=settings.AUTH_USER_MODEL, verbose_name='承办律师')),
            ],
            options={
                'verbose_name': '被告人专用介绍信',
                'verbose_name_plural': '被告人专用介绍信',
            },
        ),
        migrations.CreateModel(
            name='Defensewords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('law', models.CharField(blank=True, max_length=50, null=True, verbose_name='律师事务所')),
                ('remarks', ckeditor.fields.RichTextField(blank=True, verbose_name='意见')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Defenseword', to='criminal.Business', verbose_name='案件委托阶段')),
                ('civil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='criminal.Criminal', verbose_name='刑事案件编号')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Defensewords', to=settings.AUTH_USER_MODEL, verbose_name='承办律师')),
            ],
            options={
                'verbose_name': '辩护词',
                'verbose_name_plural': '辩护词',
            },
        ),
        migrations.CreateModel(
            name='Nonprosecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('law', models.CharField(blank=True, max_length=50, null=True, verbose_name='律师事务所')),
                ('court', models.CharField(blank=True, max_length=20, null=True, verbose_name='办案机关')),
                ('remarks', ckeditor.fields.RichTextField(blank=True, verbose_name='意见')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Nonprosecutions', to='criminal.Business', verbose_name='案件委托阶段')),
                ('civil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='criminal.Criminal', verbose_name='刑事案件编号')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Nonprosecution', to=settings.AUTH_USER_MODEL, verbose_name='承办律师')),
            ],
            options={
                'verbose_name': '不起诉意见书',
                'verbose_name_plural': '不起诉意见书',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('court', models.CharField(blank=True, max_length=20, null=True, verbose_name='办案机关')),
                ('law', models.CharField(blank=True, max_length=20, null=True, verbose_name='律师事务所')),
                ('remarks', ckeditor.fields.RichTextField(blank=True, verbose_name='意见')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Proposals', to='criminal.Business', verbose_name='案件委托阶段')),
                ('civil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='criminal.Criminal', verbose_name='刑事案件编号')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Proposal', to=settings.AUTH_USER_MODEL, verbose_name='承办律师')),
            ],
            options={
                'verbose_name': '法律意见书',
                'verbose_name_plural': '法律意见书',
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(blank=True, max_length=1000, null=True, verbose_name='案由')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='委托人/委托单位')),
                ('defendant', models.CharField(blank=True, max_length=50, null=True, verbose_name='犯罪嫌疑人或被告人')),
                ('tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='律师电话')),
                ('Trial_level', models.CharField(choices=[('1', '一审'), ('2', '二审'), ('4', '再审'), ('3', '一审，二审'), ('5', '二审，再审')], default='1', max_length=20, verbose_name='审级')),
                ('enter_date', models.DateField(verbose_name='合同有效期')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Proxy', to='criminal.Business', verbose_name='案件委托阶段')),
                ('civil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='criminal.Criminal', verbose_name='刑事案件编号')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Proxys', to=settings.AUTH_USER_MODEL, verbose_name='承办律师')),
            ],
            options={
                'verbose_name': '授权委托书',
                'verbose_name_plural': '授权委托书',
            },
        ),
        migrations.CreateModel(
            name='Risks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='委托人姓名')),
                ('remarks', ckeditor.fields.RichTextField(blank=True, verbose_name='风险告知书内容')),
            ],
            options={
                'verbose_name': '风险告知书',
                'verbose_name_plural': '风险告知书',
            },
        ),
        migrations.AddField(
            model_name='bail',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bails', to='criminal.Business', verbose_name='案件委托阶段'),
        ),
        migrations.AddField(
            model_name='bail',
            name='civil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='criminal.Criminal', verbose_name='刑事案件编号'),
        ),
        migrations.AddField(
            model_name='bail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bail', to=settings.AUTH_USER_MODEL, verbose_name='承办律师'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Appraisals', to='criminal.Business', verbose_name='案件委托阶段'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='civil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='criminal.Criminal', verbose_name='刑事案件编号'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Appraisal', to=settings.AUTH_USER_MODEL, verbose_name='承办律师'),
        ),
    ]
