# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-10 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='civils',
            name='bank',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='开户行'),
        ),
        migrations.AddField(
            model_name='civils',
            name='business',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='营业地'),
        ),
        migrations.AddField(
            model_name='civils',
            name='company_tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='公司电话'),
        ),
        migrations.AddField(
            model_name='civils',
            name='id_card',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='法定代表人身份证号'),
        ),
        migrations.AddField(
            model_name='civils',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='注册地'),
        ),
        migrations.AddField(
            model_name='civils',
            name='posts',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='职务'),
        ),
        migrations.AddField(
            model_name='civils',
            name='tak',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='税号'),
        ),
        migrations.AlterField(
            model_name='civils',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='法定代表人电话'),
        ),
    ]
