# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-02 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WxLaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.NullBooleanField(default=0, verbose_name='是否订阅')),
                ('openid', models.CharField(max_length=120, verbose_name='唯一标识')),
                ('nickname', models.CharField(max_length=64, verbose_name='用户昵称')),
                ('sex', models.IntegerField(choices=[('1', '男'), ('2', '女'), ('0', '未知')], verbose_name='性别')),
                ('province', models.CharField(max_length=64, verbose_name='省份')),
                ('city', models.CharField(max_length=64, verbose_name='城市')),
                ('country', models.CharField(max_length=64, verbose_name='国家')),
                ('language', models.CharField(max_length=12, verbose_name='国家')),
                ('headimgurl', models.CharField(max_length=240, verbose_name='国家')),
                ('subscribe_time', models.DateTimeField(null=True, verbose_name='关注时间')),
                ('unionid', models.CharField(max_length=64, null=True, verbose_name='统一标识')),
                ('remark', models.CharField(max_length=64, null=True, verbose_name='备注')),
                ('groupid', models.CharField(max_length=32, null=True, verbose_name='分组ID')),
                ('tagid_list', models.CharField(max_length=64, null=True, verbose_name='标签列表')),
                ('subscribe_scene', models.CharField(max_length=64, null=True, verbose_name='渠道来源')),
                ('qr_scene', models.IntegerField(blank=True, default=0, null=True, verbose_name='扫码场景')),
                ('qr_scene_str', models.CharField(max_length=64, null=True, verbose_name='扫码场景描述')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='wxchat', verbose_name='场景图片')),
                ('qr_time', models.DateTimeField(blank=True, null=True, verbose_name='图片创建时间')),
            ],
            options={
                'verbose_name': '微信用户信息',
                'verbose_name_plural': '微信用户信息',
            },
        ),
    ]
