# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-04 11:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('f_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='法定代表人')),
                ('tel', models.IntegerField(blank=True, null=True, verbose_name='电话')),
                ('usernames', models.CharField(blank=True, max_length=50, null=True, verbose_name='开户行')),
                ('card', models.CharField(blank=True, max_length=50, null=True, verbose_name='账号')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='地址')),
                ('enter_date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '律师事务所',
                'verbose_name_plural': '律师事务所',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='地址')),
                ('code', models.CharField(blank=True, max_length=500, null=True, verbose_name='身份证号')),
                ('law', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lawe', to='lawyer.Law', verbose_name='律师事务所')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='律师名称')),
            ],
            options={
                'verbose_name': '律师',
                'verbose_name_plural': '律师',
            },
        ),
    ]
